export const LABELS = {
  'page_title': 'SyncLift - Quick Status & Report',
  'header_subtitle': 'Quick Equipment Status Check & Reporting',
  'status_check_title': 'Check Equipment Status',
  'eq_id_placeholder': 'ID (e.g., AS-1234567890)',
  'btn_check': 'Verify',
  'report_issue_title': 'Report an Issue',
  'eq_id_to_report': 'Equipment ID',
  'type_major_breakdown': 'Major Breakdown',
  'type_maintenance_required': 'Maintenance Required',
  'type_aesthetic_issue': 'Aesthetic Issue',
  'report_desc_placeholder': 'Describe the problem...',
  'btn_submit_report': 'Submit Incident',
  'supported_eq_title': 'Supported Equipment',
  'eq_type_elevator': 'Elevators',
  'eq_type_escalator': 'Escalators',
  'eq_type_auto_door': 'Auto Doors',
  'status_ok': 'Verified OK',
  'status_due': 'Maintenance Due',
  'msg_id_required': 'Please enter an equipment ID.',
  'msg_report_success': 'Report for equipment {id} submitted successfully.',
  'msg_report_fail': 'Error submitting report. ID not found or server error.',
  'label_status': 'Current Status',
  'label_next_maint': 'Maintenance Cycle',
  'label_location': 'Sector Location',
};